basePath: /
definitions:
  apiv1.User:
    properties:
      account:
        type: string
      apples:
        type: integer
      bananas:
        type: integer
      created_at:
        type: string
      email:
        type: string
      gender:
        type: integer
      gender_str:
        type: string
      id:
        type: integer
      last_sign_in:
        type: string
      nation_code:
        type: string
      nickname:
        type: string
      phone:
        type: string
      profile:
        type: string
      whats_up:
        type: string
    type: object
  apiv1.UserUpdateRequest:
    properties:
      account:
        type: string
      gender:
        type: integer
      nickname:
        type: string
      profile:
        type: string
      whats_up:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 图书阅读器 API
  version: "1.0"
paths:
  /apiv1/book/{id}:
    get:
      parameters:
      - description: 图书id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/apiv1.User'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 获取图书详情
      tags:
      - book
  /apiv1/user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/apiv1.User'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - user
  /apiv1/user/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 修改数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/apiv1.UserUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/apiv1.User'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 修改数据
      tags:
      - user
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
